frontend:
  type: IMAGE
  source:
    type: FOLDER
    path: /home/dolu/pro/scanvan/dataset/d2
    mask: /home/dolu/pro/scanvan/dataset/mask.png
#    first: 20190319-103452-344895.bmp
#    last: 20190319-103506-594998.bmp
    scale: 1.0

#To use datapoints as viewpoint source, replace the frontend stuff with
#frontend:
#  type: CLOUDPOINT
#  model: dev/model.xyz
#  odometry: dev/odometry.xyz
#  distanceMax: 30.0
#  baseNoise: 0.001
#  badMatchNoise: 0.2
#  badMatchRate: 0.1

#To use the dense pipeline on a preprocessed odometry
#frontend:
#  type: DENSE
#  ofCacheFolder: /home/dolu/pro/scanvan/export/ofCache
#  source:
#    type: ODOMETRY
#    odometryFile: /home/dolu/pro/scanvan/export/transformation.dat
#    pictureFolder: /media/dolu/SCANVAN10TB/record/camera_40008603-40009302/20190920-172211_SionCar11
#    mask: /home/dolu/pro/scanvan/dataset/mask.png
#    scale: 0.25

matching:
  range: 5

algorithm:
  error: 1e-4
  disparity: 5
  radius: 5

# note : path has to contain a dev/ and debug/ directory
export:
  path: /media/user/Documents/model

debug:
  structureImageDump:
  lastViewPointGui:
    structureSizeMin: 5

