frontend:
  type: IMAGE
  source:
    type: FOLDER
    path: /home/dolu/pro/scanvan/dataset/d2
    mask: /home/dolu/pro/scanvan/dataset/mask.png
#    first: 20190319-103452-344895.bmp
#    last: 20190319-103506-594998.bmp
    scale: 1.0

#To use datapoints as viewpoint source, replace the frontend stuff with
#frontend:
#  type: CLOUDPOINT
#  model: dev/model.xyz
#  odometry: dev/odometry.xyz
#  distanceMax: 30.0
#  baseNoise: 0.001
#  badMatchNoise: 0.2
#  badMatchRate: 0.1

algorithm:
  error: 1e-4
  disparity: 5
  radius: 5

# note : path has to contain a dev/ and debug/ directory
export:
  path: /media/user/Documents/model

debug:
  lastViewPointGui:
    structureSizeMin: 5

