frontend:
  type: IMAGE
  source:
    type: FOLDER
    path: /home/dolu/pro/scanvan/dataset/e
    mask: /home/dolu/pro/scanvan/dataset/mask.png
algorithm:
  error: 1e-8
  disparity: 5
  radius: 3
export:
  path: /media/hamel/Documents/model
