frontend:
  type: IMAGE
  source:
    type: FOLDER
    path: /home/dolu/pro/scanvan/dataset/e
    mask: /home/dolu/pro/scanvan/dataset/mask.png

#To use datapoints as viewpoint source, replace the frontend stuff with
#frontend:
#  type: CLOUDPOINT
#  model: dev/model.xyz
#  odometry: dev/odometry.xyz

algorithm:
  bootstrap: 3
  error: 1e-6
  structure: 3
  disparity: 5
  radius_min: 1
  radius_max: 500

# note : path has to contain a dev/ and debug/ directory
export:
  path: /media/user/Documents/model

