frontend:
  type: IMAGE
  source:
    type: FOLDER
    path: /home/dolu/pro/scanvan/dataset/e
    mask: /home/dolu/pro/scanvan/dataset/mask.png
    scale: 0.125

#To use datapoints as viewpoint source, replace the frontend stuff with
#frontend:
#  type: CLOUDPOINT
#  model: dev/model.xyz
#  odometry: dev/odometry.xyz
#  distanceMax: 30.0
#  baseNoise: 0.001
#  badMatchNoise: 0.2
#  badMatchRate: 0.1

algorithm:
  error: 1e-6
  structure: 3
  disparity: 5
  radius_min: 1
  radius_max: 500

# note : path has to contain a dev/ and debug/ directory
export:
  path: /media/user/Documents/model

debug:
  lastViewPointGui:
    structureSizeMin: 5

