# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/kronos/kronos_b57b-23-6c9b/b57b-23-6c9b_scanvan/sfs-framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/kronos/kronos_b57b-23-6c9b/b57b-23-6c9b_scanvan/sfs-framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/kronos/kronos_b57b-23-6c9b/b57b-23-6c9b_scanvan/sfs-framework/CMakeFiles /media/kronos/kronos_b57b-23-6c9b/b57b-23-6c9b_scanvan/sfs-framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/kronos/kronos_b57b-23-6c9b/b57b-23-6c9b_scanvan/sfs-framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfs-framework

# Build rule for target.
sfs-framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfs-framework
.PHONY : sfs-framework

# fast build rule for target.
sfs-framework/fast:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/build
.PHONY : sfs-framework/fast

src/framework-database.o: src/framework-database.cpp.o

.PHONY : src/framework-database.o

# target to build an object file
src/framework-database.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-database.cpp.o
.PHONY : src/framework-database.cpp.o

src/framework-database.i: src/framework-database.cpp.i

.PHONY : src/framework-database.i

# target to preprocess a source file
src/framework-database.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-database.cpp.i
.PHONY : src/framework-database.cpp.i

src/framework-database.s: src/framework-database.cpp.s

.PHONY : src/framework-database.s

# target to generate assembly for a file
src/framework-database.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-database.cpp.s
.PHONY : src/framework-database.cpp.s

src/framework-feature.o: src/framework-feature.cpp.o

.PHONY : src/framework-feature.o

# target to build an object file
src/framework-feature.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-feature.cpp.o
.PHONY : src/framework-feature.cpp.o

src/framework-feature.i: src/framework-feature.cpp.i

.PHONY : src/framework-feature.i

# target to preprocess a source file
src/framework-feature.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-feature.cpp.i
.PHONY : src/framework-feature.cpp.i

src/framework-feature.s: src/framework-feature.cpp.s

.PHONY : src/framework-feature.s

# target to generate assembly for a file
src/framework-feature.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-feature.cpp.s
.PHONY : src/framework-feature.cpp.s

src/framework-frontend.o: src/framework-frontend.cpp.o

.PHONY : src/framework-frontend.o

# target to build an object file
src/framework-frontend.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-frontend.cpp.o
.PHONY : src/framework-frontend.cpp.o

src/framework-frontend.i: src/framework-frontend.cpp.i

.PHONY : src/framework-frontend.i

# target to preprocess a source file
src/framework-frontend.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-frontend.cpp.i
.PHONY : src/framework-frontend.cpp.i

src/framework-frontend.s: src/framework-frontend.cpp.s

.PHONY : src/framework-frontend.s

# target to generate assembly for a file
src/framework-frontend.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-frontend.cpp.s
.PHONY : src/framework-frontend.cpp.s

src/framework-sparsefeature.o: src/framework-sparsefeature.cpp.o

.PHONY : src/framework-sparsefeature.o

# target to build an object file
src/framework-sparsefeature.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-sparsefeature.cpp.o
.PHONY : src/framework-sparsefeature.cpp.o

src/framework-sparsefeature.i: src/framework-sparsefeature.cpp.i

.PHONY : src/framework-sparsefeature.i

# target to preprocess a source file
src/framework-sparsefeature.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-sparsefeature.cpp.i
.PHONY : src/framework-sparsefeature.cpp.i

src/framework-sparsefeature.s: src/framework-sparsefeature.cpp.s

.PHONY : src/framework-sparsefeature.s

# target to generate assembly for a file
src/framework-sparsefeature.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-sparsefeature.cpp.s
.PHONY : src/framework-sparsefeature.cpp.s

src/framework-stillcompute.o: src/framework-stillcompute.cpp.o

.PHONY : src/framework-stillcompute.o

# target to build an object file
src/framework-stillcompute.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-stillcompute.cpp.o
.PHONY : src/framework-stillcompute.cpp.o

src/framework-stillcompute.i: src/framework-stillcompute.cpp.i

.PHONY : src/framework-stillcompute.i

# target to preprocess a source file
src/framework-stillcompute.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-stillcompute.cpp.i
.PHONY : src/framework-stillcompute.cpp.i

src/framework-stillcompute.s: src/framework-stillcompute.cpp.s

.PHONY : src/framework-stillcompute.s

# target to generate assembly for a file
src/framework-stillcompute.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-stillcompute.cpp.s
.PHONY : src/framework-stillcompute.cpp.s

src/framework-structure.o: src/framework-structure.cpp.o

.PHONY : src/framework-structure.o

# target to build an object file
src/framework-structure.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-structure.cpp.o
.PHONY : src/framework-structure.cpp.o

src/framework-structure.i: src/framework-structure.cpp.i

.PHONY : src/framework-structure.i

# target to preprocess a source file
src/framework-structure.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-structure.cpp.i
.PHONY : src/framework-structure.cpp.i

src/framework-structure.s: src/framework-structure.cpp.s

.PHONY : src/framework-structure.s

# target to generate assembly for a file
src/framework-structure.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-structure.cpp.s
.PHONY : src/framework-structure.cpp.s

src/framework-transform.o: src/framework-transform.cpp.o

.PHONY : src/framework-transform.o

# target to build an object file
src/framework-transform.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-transform.cpp.o
.PHONY : src/framework-transform.cpp.o

src/framework-transform.i: src/framework-transform.cpp.i

.PHONY : src/framework-transform.i

# target to preprocess a source file
src/framework-transform.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-transform.cpp.i
.PHONY : src/framework-transform.cpp.i

src/framework-transform.s: src/framework-transform.cpp.s

.PHONY : src/framework-transform.s

# target to generate assembly for a file
src/framework-transform.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-transform.cpp.s
.PHONY : src/framework-transform.cpp.s

src/framework-utiles.o: src/framework-utiles.cpp.o

.PHONY : src/framework-utiles.o

# target to build an object file
src/framework-utiles.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-utiles.cpp.o
.PHONY : src/framework-utiles.cpp.o

src/framework-utiles.i: src/framework-utiles.cpp.i

.PHONY : src/framework-utiles.i

# target to preprocess a source file
src/framework-utiles.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-utiles.cpp.i
.PHONY : src/framework-utiles.cpp.i

src/framework-utiles.s: src/framework-utiles.cpp.s

.PHONY : src/framework-utiles.s

# target to generate assembly for a file
src/framework-utiles.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-utiles.cpp.s
.PHONY : src/framework-utiles.cpp.s

src/framework-viewpoint.o: src/framework-viewpoint.cpp.o

.PHONY : src/framework-viewpoint.o

# target to build an object file
src/framework-viewpoint.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpoint.cpp.o
.PHONY : src/framework-viewpoint.cpp.o

src/framework-viewpoint.i: src/framework-viewpoint.cpp.i

.PHONY : src/framework-viewpoint.i

# target to preprocess a source file
src/framework-viewpoint.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpoint.cpp.i
.PHONY : src/framework-viewpoint.cpp.i

src/framework-viewpoint.s: src/framework-viewpoint.cpp.s

.PHONY : src/framework-viewpoint.s

# target to generate assembly for a file
src/framework-viewpoint.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpoint.cpp.s
.PHONY : src/framework-viewpoint.cpp.s

src/framework-viewpointsource.o: src/framework-viewpointsource.cpp.o

.PHONY : src/framework-viewpointsource.o

# target to build an object file
src/framework-viewpointsource.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpointsource.cpp.o
.PHONY : src/framework-viewpointsource.cpp.o

src/framework-viewpointsource.i: src/framework-viewpointsource.cpp.i

.PHONY : src/framework-viewpointsource.i

# target to preprocess a source file
src/framework-viewpointsource.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpointsource.cpp.i
.PHONY : src/framework-viewpointsource.cpp.i

src/framework-viewpointsource.s: src/framework-viewpointsource.cpp.s

.PHONY : src/framework-viewpointsource.s

# target to generate assembly for a file
src/framework-viewpointsource.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework-viewpointsource.cpp.s
.PHONY : src/framework-viewpointsource.cpp.s

src/framework.o: src/framework.cpp.o

.PHONY : src/framework.o

# target to build an object file
src/framework.cpp.o:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework.cpp.o
.PHONY : src/framework.cpp.o

src/framework.i: src/framework.cpp.i

.PHONY : src/framework.i

# target to preprocess a source file
src/framework.cpp.i:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework.cpp.i
.PHONY : src/framework.cpp.i

src/framework.s: src/framework.cpp.s

.PHONY : src/framework.s

# target to generate assembly for a file
src/framework.cpp.s:
	$(MAKE) -f CMakeFiles/sfs-framework.dir/build.make CMakeFiles/sfs-framework.dir/src/framework.cpp.s
.PHONY : src/framework.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfs-framework"
	@echo "... src/framework-database.o"
	@echo "... src/framework-database.i"
	@echo "... src/framework-database.s"
	@echo "... src/framework-feature.o"
	@echo "... src/framework-feature.i"
	@echo "... src/framework-feature.s"
	@echo "... src/framework-frontend.o"
	@echo "... src/framework-frontend.i"
	@echo "... src/framework-frontend.s"
	@echo "... src/framework-sparsefeature.o"
	@echo "... src/framework-sparsefeature.i"
	@echo "... src/framework-sparsefeature.s"
	@echo "... src/framework-stillcompute.o"
	@echo "... src/framework-stillcompute.i"
	@echo "... src/framework-stillcompute.s"
	@echo "... src/framework-structure.o"
	@echo "... src/framework-structure.i"
	@echo "... src/framework-structure.s"
	@echo "... src/framework-transform.o"
	@echo "... src/framework-transform.i"
	@echo "... src/framework-transform.s"
	@echo "... src/framework-utiles.o"
	@echo "... src/framework-utiles.i"
	@echo "... src/framework-utiles.s"
	@echo "... src/framework-viewpoint.o"
	@echo "... src/framework-viewpoint.i"
	@echo "... src/framework-viewpoint.s"
	@echo "... src/framework-viewpointsource.o"
	@echo "... src/framework-viewpointsource.i"
	@echo "... src/framework-viewpointsource.s"
	@echo "... src/framework.o"
	@echo "... src/framework.i"
	@echo "... src/framework.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

